### ISSUE TITLE
Construction arms are missing ball joint when layered

### ISSUE THREAD

**Issue by kawilkin** [dotnet-foundation/mod-dotnet-bot#1]
Here is what it looks like in the builder:
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/47866467/97036522-ceef7800-151c-11eb-86b6-1487cdaf33cc.png)

But the SVG on its own looks fine:
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/47866467/97036534-d151d200-151c-11eb-933f-79db4db2b39a.png)

@andrewrmn Is this an SVG issue or a layering issue?

**Comment by andrewrmn** [comment]
@kawilkin Fixed!
