### ISSUE TITLE
Paragraph on home page should have left-aligned text

### ISSUE THREAD

**Issue by kawilkin** [dotnet-foundation/mod-dotnet-bot#2]
The paragraph text on the home page should have left-aligned text (the whole block is centered, but the text inside is left-aligned).

**Current:**
<img width="1337" alt="Screen Shot 2020-10-23 at 10 47 19 AM" src="https://user-images.githubusercontent.com/47866467/97036871-50dfa100-151d-11eb-9990-01e5d673bc7a.png">

**Design:**
<img width="671" alt="Screen Shot 2020-10-23 at 10 51 32 AM" src="https://user-images.githubusercontent.com/47866467/97037193-ccd9e900-151d-11eb-88cc-21f99a74d3fa.png">

**Comment by andrewrmn** [comment]
@kawilkin Done!
